name: the-pythoness

services:
  ib-gateway:
    restart: always
    image: ghcr.io/gnzsnz/ib-gateway:stable
    env_file: source/environments/ib-gateway.env
    networks:
    - ib
  ibapi-client:
    depends_on:
      - ib-gateway
    restart: no
    build:
      context: source/backend/pythoness-services/ibapi-client
      dockerfile: Dockerfile
    volumes:
      - .:/ibapi-client
    networks:
    - ib
    ports:
    - "5678:5678"
networks:
  ib: